---
# Common playbook

- hosts: common
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  roles: 
    - git-ppa
    - {role: apt-update, when: global_update_apt_cache}
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
