---
# This playbook contains common plays that will be run on all nodes.

- name: common | Install common packages 
  action: apt pkg=$item state=installed
  with_items:
    - ntp

- name: common | ntp should be running
  action: service name=ntp state=running
  tags: ntp

- name: common | Make an ansible directory for remembering what we previously run
  file: path=$common_done_dir state=directory owner=root group=root

- name: common | Generate hostname based on the ip address
  shell: touch $common_done_dir/generate-hostname && echo ip-${ansible_eth0.ipv4.address} | tr . -  creates=$common_done_dir/generate-hostname
  register: common_generated_host_name
  notify:
    - force hostname change
    - update /etc/hostname
    - update /etc/hosts

- name: common | Configure resolvconf
  dpkg_reconfigure: 
    pkg: resolvconf
    answers:
      resolvconf/downup-interfaces:
      resolvconf/linkify-resolvconf: true
      resolvconf/link-tail-to-original: true
      resolvconf/fixing-immutable:
      resolvconf/reboot-recommended-after-removal:

- name: common | Set /etc/network/interfaces
  template: src=root/etc/network/interfaces.j2 dest=/etc/network/interfaces
  notify:
    - restart interface
