---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart ntp
  service: name=ntpd state=restarted

- name: restart networking
  service: name=networking state=restarted

- name: update apt-cache
  apt: update_cache=yes

- name: restart interface
  shell: ifdown eth0 && ifup eth0 

- name: restart nscd
  service: name=nscd state=restarted

#- name: restart iptables
#  service: name=iptables state=restarted

- name: force hostname change
  command: hostname {{common_generated_host_name.stdout}}

- name: update /etc/hostname
  template: src=root/etc/hostname.j2 dest=/etc/hostname

- name: update /etc/hosts
  template: src=root/etc/hosts.j2 dest=/etc/hosts
